baseURL = 'https://jeremyckahn.github.io/'
languageCode = 'en-us'
title = "Observe and Report"
theme = "hugo-bearcub"
Copyright = "[Jeremy Kahn](https://github.com/jeremyckahn/)"

[params]
  madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
